### ISSUE TITLE
🐛 Bug Report: Project Settings or Feedback Not Visible

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/console#1008]
### 👟 Reproduction steps

Project Settings & the Feedback options are visible on either Desktop or Mobile sized window.
If the window size is anywhere in the middle, like resized, on maybe on a tablet like device, the Settings & the Feedback option is not shown.

---
See -

<img width="923" alt="Missing options" src="https://github.com/appwrite/console/assets/20625965/57b6beda-647f-49d7-8831-95c82b0f92b2">

### 👍 Expected behavior

Show the missing options.

### 👎 Actual Behavior

Options are missing.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

Affects Cloud & all the versions ahead.
1. Safari : Version 17.4.1 (19618.1.15.11.14)
2. Chrome : Version 123.0.6312.105 (Official Build) (arm64)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by FatumaA** [comment]
Can reproduce this

**Comment by stnguyen90** [comment]
@ItzNotABug, thanks for raising this issue! 🙏🏼 Looks like we're using `is-only-mobile` when we should be using `is-not-desktop` here:

https://github.com/appwrite/console/blob/da41df2481e7a1219ce91d645d13a507f1a010c3/src/lib/layout/navigation.svelte#L200

and here

https://github.com/appwrite/console/blob/da41df2481e7a1219ce91d645d13a507f1a010c3/src/lib/layout/navigation.svelte#L227

**Comment by FatumaA** [comment]
If @ItzNotABug doesn't mind, I'll like to do it 🙂
Been looking to start contributing to this repo

**Comment by stnguyen90** [comment]
@FatumaA, assigned! Thanks for your interest!
