### ISSUE TITLE
🐛 Bug Report: Can't select runtime (python, phd, node) in self-hosted appwrite function template

### ISSUE THREAD

**Issue by vule20** [appwrite/console#1011]
### 👟 Reproduction steps

Hey all. I'm hosting my own appwrite server and I've succesfully connected my appwrite to my github app. However, for some function templates such as generate pdf, I can't select runtime for deployment. For the starter template, I was able to choose different runtime type

### 👍 Expected behavior

It should be able to select several runtime types

### 👎 Actual Behavior

Can't select runtime (python, phd, node) in self-hosted appwrite function template

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Linux

### 🧱 Your Environment

I use appwrite 1.4.13. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by anthony-dl** [comment]
https://github.com/appwrite/console/assets/63137043/8658677f-fc64-465d-a33f-752a26f6c0f8

**Comment by ItzNotABug** [comment]
This happens because the only supported runtime for the function on your `appwrite` instance is `node-18.0` and also due to [this](https://github.com/appwrite/console/blob/737457c1446318c4f39fcc373024537af1bc09b6/src/lib/wizards/functions/steps/templateConfiguration.svelte#L55C13-L62C56) which doesn't seem to set a visible default runtime item.

**Comment by ItzNotABug** [comment]
Hey Appwrite Team,
Can I be assigned to work on this?

**Comment by anthony-dl** [comment]
Thanks for the reply. Actually the function Generate PDF from Appwrite template supports multiple runtime types.

**Comment by ItzNotABug** [comment]
Yes, but this happens when the runtime installed on your `appwrite` instance is only `node-18`. Dropdown is shown when you have more than one supported runtime.

**Comment by Meldiron** [comment]
Assigning @ItzNotABug , his findings seem relevant. Thanks both for participating in the issue, can' wait to review the PR 🥳
