### ISSUE TITLE
🐛 Bug Report: Project creates two times

### ISSUE THREAD

**Issue by Honzoraptor31415** [appwrite/console#1033]
### 👟 Reproduction steps

1. Go to the console `https://cloud.appwrite.io/console`
2. Click "Create project"
3. Go trough the setup proccess

### 👍 Expected behavior

It should take me to the new project page right after clicking the button (of course with some delay because of some async stuff).

### 👎 Actual Behavior

At the end after clicking the "Create" button, nothing happens even after waiting a few seconds, but after I click it the second time, it takes me to the new project page. However now when I go to the console again, I can see two projects named the same, even tho I just wanted created one.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

_Also I apologise for accidentally creating the issue in the website repo, I had to move it here_

**Comment by ItzNotABug** [comment]
Can reproduce this, probably a state management issue which re-enables the `Create` button before the setup is completed.

I proceeded to click the `Create` three times and 3 projects were created. Also note, if you provide a Project ID then the multiple projects will not be created and an error will be thrown.

**Comment by Honzoraptor31415** [comment]
> Can reproduce this, probably a state management issue which re-enables the `Create` button before the setup is completed.
> 
> I proceeded to click the `Create` three times and 3 projects were created. Also note, if you provide a Project ID then the multiple projects will not be created and an error will be thrown.
> 
> Probable source -
> 
> https://github.com/appwrite/console/blob/737457c1446318c4f39fcc373024537af1bc09b6/src/lib/layout/wizard.svelte#L103-L105

Does the setTimeout() function have any purpose? Because I feel like this part of code doesn't make sense with the timeout there.

**Comment by ernstmul** [comment]
This is fixed in a recent release
