### ISSUE TITLE
🐛 Bug Report: Some items in the search dialog don't work

### ISSUE THREAD

**Issue by Honzoraptor31415** [appwrite/console#1042]
### 👟 Reproduction steps

1. Go to [the console](https://cloud.appwrite.io/console)
2. Click the 
![search-icon](https://github.com/appwrite/console/assets/151644171/c0b5df2d-0ff7-4f13-931c-4cf5275d035d)
search icon
3. Scroll a little to the `Security` or `Settings` section
![security-section](https://github.com/appwrite/console/assets/151644171/29cca786-d611-4016-9d04-a13b3b9a642e)
4. Click any of the items in those two sections

### 👍 Expected behavior

It should do something (maybe show a pop-up, maybe take me to another page)

### 👎 Actual Behavior

After clicking any of the items in the `security` section, the search dialog closes and an error gets logged:
![error-screenshot](https://github.com/appwrite/console/assets/151644171/89028d57-e8bb-4906-b9ee-a0d569792425)
And also I found out that a different error gets logged when using Firefox as a browser:
![firefox-screenshot](https://github.com/appwrite/console/assets/151644171/f1fd8dd6-f97c-4ba9-99d2-d15e80925718)
And if you click one of the items in the `settings` section, the search dialog will remain open.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by naman1608** [comment]
@FatumaA yes these work when we are within a project and `project.$id` exists, maybe these should be disabled when `project.$id` is null?

**Comment by Honzoraptor31415** [comment]
> @FatumaA @stnguyen90 yes these work when we are within a project and `project.$id` exists, maybe these should be disabled when `project.$id` is null?

Agree, we just need a pr for it now

**Comment by naman1608** [comment]
> > @FatumaA @stnguyen90 yes these work when we are within a project and `project.$id` exists, maybe these should be disabled when `project.$id` is null?
> 
> Agree, we just need a pr for it now

I have put a PR for it, https://github.com/appwrite/console/pull/1131

**Comment by Honzoraptor31415** [comment]
> > > @FatumaA @stnguyen90 yes these work when we are within a project and `project.$id` exists, maybe these should be disabled when `project.$id` is null?
> > 
> > 
> > Agree, we just need a pr for it now
> 
> I have put a PR for it, #1131

Awesome job, I'll close the issue once the PR gets merged!

**Comment by stnguyen90** [comment]
Great work @naman1608! 🚀 And thanks, @Honzoraptor31415, for raising this! 🙏🏼
