### ISSUE TITLE
🐛 Bug Report:  Bucket Ui Alignment issue

### ISSUE THREAD

**Issue by Sourav0010** [appwrite/console#1044]
### 👟 Reproduction steps

1. navigate to appwrite website
2. then login to your personal account or create one if not there
3. create a project or navigate to project
4. Click on Storage Link on left hand option link
5. Create a bucket and open dev tools on chrome
6. then open responsive design
7. and set it to 762px 
8. then check that the encrypted and antivirus icon it's overflowing the bucket box.

![1229849345030098946remix-1713289383447](https://github.com/appwrite/console/assets/76106639/fbbbb103-f70f-4cb4-a86c-0c6b28d969fa)

### 👍 Expected behavior

It should be properly aligned.

### 👎 Actual Behavior

When the screen size goes below 762px  the encryption and antivirus icon of each bucket overflowing

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 🧱 Your Environment

I used the version of appwrite (v1.4.13)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ernstmul** [comment]
This has been fixed in a recent release
