### ISSUE TITLE
Remove support illustration

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/console#1060]
Remove the illustration so it should look like:

![image](https://github.com/appwrite/console/assets/1477010/ef76ab86-73f8-47de-95c5-f21fe2963553)

_Originally posted by @stnguyen90 in https://github.com/appwrite/console/pull/935#discussion_r1558212503_

**Comment by ItzNotABug** [comment]
Hey @stnguyen90, ig I completely missed this required change in the existing PR. The support executive illustration seems to be no longer required

Do you want me to create a separate PR or refactor the existing one? Again, my bad I missed this 😅

**Comment by stnguyen90** [comment]
@ItzNotABug, haha no worries! I want to minimize changes to your existing PR so that, hopefully, it can get merged sooner. What you can do is create a new PR with your previous branch (`ItzNotABug:refactor-933-use-local-timings-for-premium-support`) as the base.

**Comment by ItzNotABug** [comment]
@stnguyen90 what should be the case if the account isn't a paid account?
I was thinking of using a common message for both the types like below but the CTA would differ -

<table border="1">
    <tr>
        <td><img src="https://github.com/appwrite/console/assets/20625965/ba828d1f-2c1c-4d6f-b7a9-cf66d62c76c2" alt="support" height="275"></td>
        <td><img src="https://github.com/appwrite/console/assets/20625965/0979c101-0b6f-4fca-8674-3dd8ecfe2736" alt="support.premium" height="275"></td>
    </tr>
</table>

**Comment by stnguyen90** [comment]
> what should be the case if the account isn't a paid account? 

Does it need to change? The current behavior hides the "Get personalized support ..." text if a user is on the Starter plan, right?

**Comment by ItzNotABug** [comment]
@stnguyen90 Yupp, but it would look like -

```
Premium Support
[Get Premium Support]
```

Doesn't seem that nice, looks a tad repetitive. Also adding the default timings would let the user know about the working hours.

**Comment by stnguyen90** [comment]
@ItzNotABug, it might be good to create the PR and share the screenshot of what it'll look like. Then, I can show it to design to sign off on it.
