### ISSUE TITLE
🐛 Bug Report: Not enough padding for danger cards

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/console#1086]
### 👟 Reproduction steps

On a window less than 767px

1. Log in to the Console
2. Click on the user in the top right
3. Click on "Your account"
4. Scroll down to "Delete account"

### 👍 Expected behavior

There is some padding after the danger alert

### 👎 Actual Behavior

There is no padding:

<img width="760" alt="image" src="https://github.com/appwrite/console/assets/1477010/efe8c02a-25c7-4a76-865e-fc47a93eef3d">

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
still a problem on 1.5.6

**Comment by ItzNotABug** [comment]
Related: https://github.com/appwrite/console/issues/918.

**Comment by elad2412** [comment]
Hi @stnguyen90 here is PR for this issue:
https://github.com/appwrite/console/pull/1107
