### ISSUE TITLE
🐛 Bug Report: Typo in Console - functions -> Executions -> limits btn

### ISSUE THREAD

**Issue by RoiEf** [appwrite/console#1109]
### 👟 Reproduction steps

Select a function and open the executions tab.
Click the "Limits applied" button.
There's a $ - a dollar sighn in front of the '1' number. 

### 👍 Expected behavior

It shuld show a text like the word "per".

### 👎 Actual Behavior

There's a $ - a dollar sighn in front of the '1' number. 

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@RoiEf, thanks for creating this issue! 🙏🏼 

Screenshot for reference:

![image](https://github.com/appwrite/console/assets/1477010/21279588-3bf2-415b-bbc2-0a3fbdd5c481)

**Comment by stnguyen90** [comment]
here's the `hoursToDays()` function:

https://github.com/appwrite/console/blob/24d03618429e4db6e836ccc1d99cc0ccb789f4c9/src/lib/helpers/date.ts#L152-L158

we should probably add some tests for that and verify it's working as expected.

**Comment by stnguyen90** [comment]
Actually, looks like this should be fixed as part of https://github.com/appwrite/console/pull/1106
