### ISSUE TITLE
🚀 Enhancement: Add Python (ML) starter template

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/console#1132]
### 🔖 Enhancement description

If I:

1. Go to functions
2. Click the "Create function" button
3. Select Python
4. Click on the "Runtime" dropdown

I don't see the Python (ML) runtime:

<img width="1070" alt="image" src="https://github.com/appwrite/console/assets/1477010/66fe9c00-0a56-4ce1-9fdf-b03db004ee54">

For reference, the [blog](https://appwrite.io/blog/post/introducing-python-machine-learning-runtime) suggests:

![image](https://github.com/appwrite/console/assets/1477010/27c199e7-31c9-4a5f-9796-c118611da9ea)

It would be nice to be able to easily create a blank/starter Python (ML) runtime function.

### 🎤 Pitch

The problem right now is it seems like something is broken/missing when you try to create a Python (ML) runtime function because the option isn't available.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by naman1608** [comment]
@stnguyen90 I was exploring how the functions are created for each runtime and found a call to `https://cloud.appwrite.io/v1/functions` with the runtime as part of the payload, so for Python (ML), this endpoint should be able to handle it right? How can I check if it does or not?
