### ISSUE TITLE
🐛 Bug Report: GPDR violation in self-hosted Console by monitoring through Sentry without consent or transparency

### ISSUE THREAD

**Issue by ttrinidad** [appwrite/console#1169]
### 👟 Reproduction steps

Using self-hosted Appwrite Console in production environment we can see see it pings back to Sentry without consent and without clear option to disable it (other than not using ENV.PROD) which a major privacy concern and legally against GPDR and other similar online privacy and data protection legislation.

### 👍 Expected behavior

To cease violation of GPDR and similar legislation and treat user private data with "Lawfulness, fairness and transparency", as well as having the common courtesy expected of not leaking private information without consent or at least telling people about it.

### 👎 Actual Behavior

Attempting to contact Sentry always, because of:
https://github.com/appwrite/console/blob/0fdd92b89c4195c294fb88d200f23ea52eb8420d/src/routes/%2Blayout.svelte#L49

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

[Version 1.5.7](https://github.com/appwrite/appwrite/releases)
Installed using Coolify

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Meldiron** [comment]
Thanks for reporting this 🙌  Regarding GDPR, that could possibly be a problem for Cloud users too. Not a legal expert, but I believe collecting anonymous data is considered GDPR-safe.

With that said, this implementation was meant for usage on Cloud domains only, as an experiment to ensure it provides value. Later we planned to support it on self-hosting if we see good insights.

**Comment by TorstenDittmann** [comment]
@ttrinidad This has been removed in the 5.0.0 version of the console and will be released with 1.6.x of https://github.com/appwrite/appwrite 🙏🏻
