### ISSUE TITLE
🐛 Bug Report: Unable to clone code repository: fatal: '0.1.*' is not a valid branch name when creating new function

### ISSUE THREAD

**Issue by rinae-del** [appwrite/console#1279]
### 👟 Reproduction steps

Create a new account then add a new function.

### 👍 Expected behavior

Should successfully build the function.

### 👎 Actual Behavior

Build failed with:

```
Unable to clone code repository: fatal: '0.1.*' is not a valid branch name. If you redeploy, error changes to Docker Error: Preparing for build ... cp: can't stat '/mnt/code/*': No such file or directory
```

![qOnkgBDh](https://github.com/user-attachments/assets/178fd7f5-bf26-4995-beb9-f272e27e66ef)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
This should be resolved now.
