### ISSUE TITLE
🚀 Enhancement: Show notification after adding (and verifying) authenticator

### ISSUE THREAD

**Issue by stnguyen90** [appwrite/console#1298]
### 🔖 Enhancement description

After adding (and [verifying](https://github.com/appwrite/console/blob/f664172c338f39242bf8b5f589eddb51d150efb7/src/routes/console/account/mfa.svelte#L29)) an authenticator, the console should show a notification saying:

> Authenticator has been added

similar to how we show a notification after enabling/disabling MFA:

https://github.com/appwrite/console/blob/f664172c338f39242bf8b5f589eddb51d150efb7/src/routes/console/account/updateMfa.svelte#L33-L36

### 🎤 Pitch

This gives user feedback that something happened successfully.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this! Just to clarify, the notification should be shown both after adding and after verifying? If this is the case should the messages then be "Authenticator has been added" (for `addAuthenticator()`) and "Authenticator has been verified" (for `verifyAuthenticator()`)?
