### ISSUE TITLE
🐛 Bug Report: 'TypeError: o[0].rules[0] is undefined' when trying to execute function

### ISSUE THREAD

**Issue by hej2010** [appwrite/console#1360]
### 👟 Reproduction steps

Go to a function and press Execute in the console.

### 👍 Expected behavior

The execution window should show.

### 👎 Actual Behavior

The execution window does not show and the page content disappears.
Logs:
```
Uncaught (in promise) TypeError: o[0].rules[0] is undefined
    Immutable 43
    <anonymous> https://website.com/console/project-0/functions/function:187
    promise callback* https://website.com/console/project-0/functions/function:186
    promise callback* https://website.com/console/project-0/functions/function:180
```
Error in `DeploymentDomains.XXX.js`
![bild](https://github.com/user-attachments/assets/f23180a0-0b02-441c-bae0-a9352b62af48)

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 1.6.0
Appwrite console 5.0.12
Self-hosted
No function domains

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by hej2010** [comment]
If I create a domain for the function it works and I can execute it, but as soon as I delete the domain it gets the same error.

**Comment by ibaraki-douji** [comment]
I also have the issue with functions with no domains on it.

File where the error happen :
https://github.com/appwrite/console/blob/main/src/routes/(console)/project-%5Bproject%5D/functions/function-%5Bfunction%5D/deploymentDomains.svelte

Related discord support post :
https://discord.com/channels/564160730845151244/1286406438666895544

**Comment by TheAndreDev** [comment]
I’m encountering the same problem with the same error in the browser console. I’m having trouble creating a new domain for the functions, which means I have to recreate them from GitHub when I want to test them from the console. This is really annoying.
