### ISSUE TITLE
🐛 Bug Report: Redirect fails after logout

### ISSUE THREAD

**Issue by imtia33** [appwrite/console#1515]
### 👟 Reproduction steps

In appwrite cloud when clicked on account icon some options come up which contains sign out button. This works fine to logout and redirect to appwrite's sign in page.
But instead when you click "your account"  option and click the logout option appears there, there is a error like this. ![Image](https://github.com/user-attachments/assets/2591ddc0-f0dc-45f9-bb58-9c0e12d8bf35)
1. It doesnt redirects the user. 
2. The account icon option is still there (I think the webpage thinks that its still logged in but in fact it isnt).
3. The buttons doesnt work to go to appwrite homepage (i.e. the logo) also the back to console doesnt work the screen persist.
For this i would have to open a new tab and then try to login which works fine. 
But the prev tab is fixed on the error. Also in the url section it shows a weird org id ![Image](https://github.com/user-attachments/assets/77ede2a7-889a-4517-8b04-532782042917)

### 👍 Expected behavior

It should redirect user to the signup or homepage of appwrite.

### 👎 Actual Behavior

Error:401
User(role:guest) missing scope (account)
And the screen persist.

### 🎲 Appwrite version

Version 1.6.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [x] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [x] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related thread: https://discord.com/channels/564160730845151244/1306267333953847346

**Comment by ernstmul** [comment]
PR with fix: https://github.com/appwrite/console/pull/1516
