### ISSUE TITLE
🐛 Bug Report: Project is not creating from console

### ISSUE THREAD

**Issue by Faiyyaz** [appwrite/console#200]
### 👟 Reproduction steps

Try to create a project using console

### 👍 Expected behavior

It should create the project

### 👎 Actual Behavior

The server returns server error and the project is not creating

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@Faiyyaz, thanks for raising this issue! Would you please provide more info on the error as well as the logs from the appwrite container?

**Comment by Faiyyaz** [comment]
@stnguyen90 Sure. Can you let me know how to get logs from appwrite container?

**Comment by stnguyen90** [comment]
@Faiyyaz `docker compose logs appwrite`. 

Would you please also provide the exact version you're on?

**Comment by Faiyyaz** [comment]
Please find attached screenshot of error from console and appwrite logs

<img width="1440" alt="Screenshot 2022-12-12 at 10 28 42 AM" src="https://user-images.githubusercontent.com/18116236/206964318-92ac74f9-4256-4a15-8b7e-91792d8db2a5.png">

<img width="1440" alt="Screenshot 2022-12-12 at 10 30 29 AM" src="https://user-images.githubusercontent.com/18116236/206964418-fcd0246e-5792-4149-a004-25b618aff350.png">

**Comment by Faiyyaz** [comment]
@stnguyen90 I reinstalled the docker and now everything seems to be working. Thank you for your help!
