### ISSUE TITLE
🐛 Bug Report: Window is not defined

### ISSUE THREAD

**Issue by iswarmondal** [appwrite/console#221]
### 👟 Reproduction steps

- I cloned the console repo for appwrite
- I configured the `.env.example` file with the credentials of my local instance of Appwrite
- After installing the dependencies on my local system just did `npm run dev`
- The app didn't even run, just throws the error `ReferenceError: window is not defined`. The error is coming form `src/lib/stores/sdk.ts`.
- Here in the `sdk.ts` file on line number `16` the error is seems to be located at

### 👍 Expected behavior

After configuring the env file and installing the dependencies the app is suppose to run without errors

### The app is throwing this error
![image](https://user-images.githubusercontent.com/73457704/208436766-31557e80-c92a-43d9-a69c-0cb6e9e90c51.png)

### Here is the typescript error in `src/lib/stores/sdk.ts`
![image](https://user-images.githubusercontent.com/73457704/208437156-cb796518-47c5-405e-a74a-b8c05e52b7dd.png)

### 🎲 Appwrite version

Version 1.1.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I'm running Appwrite on my local machine using docker.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
Hi @iswarmondal, thank you for the feedback :pray: 

Did you remember to rename the `.env.example` file to just `.env`?

**Comment by iswarmondal** [comment]
Hey @ArmanNik thanks for pointing out, that solved the issue. Now it's running as it suppose to be.

Now I'm thinking should that be mentioned in the docs for new contributors like me.

**Comment by ArmanNik** [comment]
@iswarmondal I'm happy to hear that the problem was fixed :blush: 

Yes, I agree. It definitely should be mentioned in the docs :100:

**Comment by stnguyen90** [comment]
Related PR: https://github.com/appwrite/console/pull/219
