### ISSUE TITLE
🚀 Feature: ability to search / filters through collections

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/console#318]
### 🔖 Feature description

You guys should add search / filters to the collections.

### 🎤 Pitch

it's difficult to find document you guys add search / filters to the collections.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@usamashafiqs thank you for your feedback :pray:

**Comment by FernandoUFS** [comment]
I also need this feature. It has been very hard to test and find collections. In the image you see I have 353 collections of chat, these collections are named, but I can't just search one by name.

![image](https://user-images.githubusercontent.com/5408926/222770405-1db20b50-b7b6-416d-9949-ec888d961d50.png)

**Comment by stnguyen90** [comment]
FYI, this is in the works.

Related issues:

* https://github.com/appwrite/appwrite/issues/4979

**Comment by jatingodnani** [comment]
@stnguyen90 you can assign this issue to me

**Comment by stnguyen90** [comment]
Closing this in favor of https://github.com/appwrite/appwrite/issues/4979. Please 👍🏼 https://github.com/appwrite/appwrite/issues/4979
