### ISSUE TITLE
🐛 Bug Report: Showing toast with inverse message when enabling/disabling OAuth2 Providers

### ISSUE THREAD

**Issue by probablyArth** [appwrite/console#383]
### 👟 Reproduction steps

- Click on any OAuth2 Provider in settings
- fill the form
- Click on update

### 👍 Expected behavior

It should show "enabled" in the toast when enabling an OAuth2 Provider instead of showing "disabled".

### 👎 Actual Behavior

![image](https://user-images.githubusercontent.com/61962871/230774106-4b0f62ec-d305-4e7a-b55c-976c08ef94e0.png)
The toast is indicating that github authentication has been disabled even though it's enabled.

### 🎲 Appwrite version

Version 1.2.x

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite Console

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by probablyArth** [comment]
Its the same when disabling an OAuth2 Provider

**Comment by joeyouss** [comment]
Hi, thank you for reporting this error. I tried it right now and seems like this is indeed happening. Allow me to communicate with my team and get back

**Comment by adityaoberai** [comment]
@joeyouss I also checked and can confirm that the message is incorrect.

**Comment by joeyouss** [comment]
Awesome, sounds good @probablyArth - assigning it to you

**Comment by probablyArth** [comment]
It seems that it has already been fixed with "updated" in the main branch @joeyouss @adityaoberai 
![image](https://user-images.githubusercontent.com/61962871/230920456-e4ced0c3-d290-4f37-9342-0752213d6b30.png)

**Comment by joeyouss** [comment]
Awesome!
