### ISSUE TITLE
🚀 Feature: ability to search through documents

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/console#396]
### 🔖 Feature description

You guys should add search to the documents.

### 🎤 Pitch

it's difficult to find document you guys add search to the documents.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@usamashafiqs I believe this may not be feasible. To search through documents, an index is needed, which must be generated by hand by the user :blush:

**Comment by t0mm4rx** [comment]
Hello @ArmanNik , I think it's possible even without an index on every field. Check out this tool we developed to solve the same issue as the OP: https://github.com/ScalaeStudio/appwrite-db-explorer.
