### ISSUE TITLE
🐛 Bug Report: Console UI Attributes of document entry unreadable in collection view.

### ISSUE THREAD

**Issue by Gizmo1337** [appwrite/console#402]
### 👟 Reproduction steps

Switching to other collections from the side panel to a collection with a lot of attributes results in a fixed-width unscrollable horizontal table.

<img width="269" alt="Screenshot 2023-04-14 at 11 15 55" src="https://user-images.githubusercontent.com/25569867/231986153-69ee0fe5-2827-4e7b-a0b1-ac32ad775136.png">

![image](https://user-images.githubusercontent.com/25569867/231985465-906b91a7-cb7d-49f1-83f5-e97a058a8177.png)

### 👍 Expected behavior

Display the full extent of the attribute name and fit relevant attribute content.

### 👎 Actual Behavior

Having a lot of attributes will divide the space between all the elements.

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by ArmanNik** [comment]
@Gizmo1337 thank you for the feedback :pray:

**Comment by yatharth1706** [comment]
Hi @joeyouss , I would love to give it a try. Can i work on this issue ?

**Comment by stnguyen90** [comment]
@yatharth1706, are you still interested in working on this?

**Comment by ArmanNik** [comment]
@TGlide didn't we fix this already?

**Comment by TGlide** [comment]
> @TGlide didn't we fix this already?

We did 🤔 This is odd. The latest version of the console (on `main`) doesn't show this issue as far as I can tell.

**Comment by stnguyen90** [comment]
Yes, this should be fixed in 1.4:

![image](https://github.com/appwrite/console/assets/1477010/57f43ae7-9008-4ebc-bb13-4b90a500fc2c)
