### ISSUE TITLE
🐛 Bug Report: Failed index still gives "Index Created" message

### ISSUE THREAD

**Issue by Sirius3615** [appwrite/console#430]
### 👟 Reproduction steps

When I make an Index that would throw an error/fail it shows it failed but it also pops a small banner in the top right corner saying the index was created with a green tick, seems a bit off.

### 👍 Expected behavior

It should either change the banner to something that would indicate it failed or not show it at all.

### 👎 Actual Behavior

https://user-images.githubusercontent.com/73075021/235786454-78996c91-e676-496d-83d0-7683ac5a7f45.mov

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

MacOS

### 🧱 Your Environment

Appwrite Cloud Console (In Safari)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for opening this. I have conveyed this to my team

**Comment by stnguyen90** [comment]
@Sirius3615, I can see how

> Index has been created

can be confusing/misleading. Since the index creation is done in the background by a worker, we should change this to:

 > Creating index

**Comment by Chaitanya-Upadhye** [comment]
> can be confusing/misleading. Since the index creation is done in the background by a worker, we should change this to:
 
>  Creating index

Should the notification be of the type `info` in this case ? since we are not certain of the outcome?

Would someone be able to assign this to me? I can take this up! @joeyouss @stnguyen90

**Comment by stnguyen90** [comment]
> Should the notification be of the type `info` in this case ? since we are not certain of the outcome?

No, it should still be success because the request to create the index was successful.
