### ISSUE TITLE
🚀 Feature request : CI - ignore some files in event trigger of `tests` GHA 

### ISSUE THREAD

**Issue by Ananya2001-an** [appwrite/console#462]
### 🔖 Feature description

We should add `paths-ignore` to event triggering config since running tests where it's not needed is a bit unnecessary...like for the .md files

### 🎤 Pitch

```yaml
paths-ignore:
      - '.gitignore'
      - '**.md'
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by Ananya2001-an** [comment]
I can raise a PR for it if approved :)

**Comment by joeyouss** [comment]
Hi @Ananya2001-an , this would be a good PR to have. You can take this up and move forward! Assigning this issue to you.
