### ISSUE TITLE
🐛 Bug Report: Modal should be in the center instead of corner for better visibility and UX

### ISSUE THREAD

**Issue by manaver** [appwrite/console#463]
### 👟 Reproduction steps

When i am deleting my custom domain a blank screen appears and the modal for deleting is not showing there.

### 👍 Expected behavior

The modal should be in the center.
I checked it through inspect in my browser and from there I found out that it is settled in the bottom instead of center.

### 👎 Actual Behavior

Here's the demo of this issue:
[Screencast from 13-06-23 10:31:19 PM IST.webm](https://github.com/appwrite/console/assets/78682260/8083374c-f684-4ece-9f58-28dd1ec25bd9)
Also some other pages have the same problems too.
Like create collection page:
![245566220-f884f82f-f260-452a-945d-d524b1422a5e](https://github.com/appwrite/console/assets/78682260/70932347-89ba-4b54-884f-32545f0600ed)

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by manaver** [comment]
I want to work on this issue. Can i work on this issue?

**Comment by joeyouss** [comment]
I would love to assign it to you but first I need a confirmation from the console team if this was intentional and/or requires change. Tagging @TGlide here for feedback on this.

**Comment by manaver** [comment]
> I would love to assign it to you but first I need a confirmation from the console team if this was intentional and/or requires change. Tagging @TGlide here for feedback on this.

Hi, I also found out that this error is only coming in  edge I used in ubuntu. I tried open this in  firefox and it is working fine.?

**Comment by joeyouss** [comment]
> Hi, I also found out that this error is only coming in edge I used in ubuntu. I tried open this in firefox and it is working fine.?

It could be browser specific

**Comment by manaver** [comment]
> 
> 
> > Hi, I also found out that this error is only coming in edge I used in ubuntu. I tried open this in firefox and it is working fine.?
> 
> It could be browser specific 

I think I will close the issue? Its can be because the edge in ubuntu needs bug fixing?
