### ISSUE TITLE
📚 Documentation: Apple App code snippet for step 3 throws `Extraneous argument label 'status:' in call` in Xcode

### ISSUE THREAD

**Issue by erezhod** [appwrite/console#467]
### 💭 Description

When creating a new `Apple App` from the console and reaching [step 3](https://github.com/appwrite/console/blob/58813c1bba9ea2ce4ccddcb3804c96b774afbd04/src/routes/console/project-%5Bproject%5D/overview/platforms/wizard/apple/step3.svelte), the following code snippet appears:

```swift
let client = Client()
    .setEndpoint("http://localhost:3000/v1")
    .setProject("6496fd6f36368405265d")
    .setSelfSigned(status: true) // For self signed certificates, only use for development
```

When implemented in Xcode, it throws the following error: `Extraneous argument label 'status:' in call`, since the correct signature for the `setSelfSigned` method from the [sdk-for-apple](https://github.com/appwrite/sdk-for-apple/blob/37a38679d62b2a500cd64c9e7a23e2eee8ed84e7/Sources/Appwrite/Client.swift#L145) repo on line 145, requires no implementation of the `status:` label.

```swift
open func setSelfSigned(_ status: Bool = true) -> Client
```

Also, wasn't sure if this counts as a bug or a documentation issue, so I went with documentation. Hopefully it's not a problem.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by erezhod** [comment]
I will be releasing a pull request with a fix for this in a few minutes 🙃

**Comment by erezhod** [comment]
Pull request #468 awaiting review.

**Comment by stnguyen90** [comment]
@erezhod thanks for raising this! We'll take a look at the PR soon!
