### ISSUE TITLE
🐛 Bug Report: Single links instead of plural one.

### ISSUE THREAD

**Issue by byawitz** [appwrite/console#470]
### 👟 Reproduction steps

In this file 
https://github.com/appwrite/console/blob/9174d8f8cb584744dd7a53f69d324f490ee82ee3/src/lib/layout/logs.svelte

Two dynamically generated links use a singular path instead of a plural one.

**deployment** instead of **deployments**
https://github.com/appwrite/console/blob/9174d8f8cb584744dd7a53f69d324f490ee82ee3/src/lib/layout/logs.svelte#L20

**execution** instead of **executions**
https://github.com/appwrite/console/blob/9174d8f8cb584744dd7a53f69d324f490ee82ee3/src/lib/layout/logs.svelte#L28

### 👍 Expected behavior

Links should point to 
- [Deployments](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/functions.php#L848) endpoint 
- [Executions](https://github.com/appwrite/appwrite/blob/master/app/controllers/api/functions.php#L1285) endpoint

### 👎 Actual Behavior

...

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Thank you for the PR, I would pass this for review to the concerned team and get it reviewed ASAP.
