### ISSUE TITLE
🐛 Bug Report: Incorrect accounting for registered users based on time

### ISSUE THREAD

**Issue by AidenY69** [appwrite/console#476]
### 👟 Reproduction steps

Go to the console, click Auth, and select one of the timer periods: 24h, 30d, 90d

### 👍 Expected behavior

It will show the cumulative registered users for that time period selected

### 👎 Actual Behavior

It shows the registered users based on the last 'bar' from the graph, not the cumulative number based on the time selected:

24 hours:
![image](https://github.com/appwrite/console/assets/120392135/73cd3b29-1ee4-46ca-ab37-8cfbe582325a)

30d:
![image](https://github.com/appwrite/console/assets/120392135/c891cbe6-c234-4a0b-a4a4-52dafd455703)

90days:
![image](https://github.com/appwrite/console/assets/120392135/2e145bc4-c9cf-4a44-be69-072ff3f7c1d9)

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Closing as we plan on rewriting the usage logic as part of https://github.com/appwrite/appwrite/issues/4751
