### ISSUE TITLE
🐛 Bug Report: example JSON for function execution is incorrect syntactically 

### ISSUE THREAD

**Issue by Ananya2001-an** [appwrite/console#477]
### 👟 Reproduction steps

Go to:
Functions -> Your function -> Execute now -> Enable "show example json"

### 👍 Expected behavior

The example JSON has incorrect syntax:
![Screenshot 2023-07-08 215545](https://github.com/appwrite/console/assets/55504616/d253cc67-d621-4d1f-8772-dfd6a67c0e29)

### 👎 Actual Behavior

The keys should be strings only.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi @Ananya2001-an , this is a known issue and is under fixing. So, this will be taken care of in the future release.

**Comment by stnguyen90** [comment]
Closing as a duplciate of https://github.com/appwrite/appwrite/issues/4940
