### ISSUE TITLE
🐛 Bug Report: Error loading some assets

### ISSUE THREAD

**Issue by DH-555** [appwrite/console#545]
### 👟 Reproduction steps

After some time, randomly, The console starts showing all texts underlined, and some elements like buttons are misformed. This seemed to be a Cloudflare caching issue, since after purging cache and deleting all browser data it started working again, but after setting a rule to override caching, the same error persists some times.

This happens in Firefox mainly and some times in chrome.

### 👍 Expected behavior

Obviously that should not happen

### 👎 Actual Behavior

![Captura de pantalla 2023-09-13 120232](https://github.com/appwrite/console/assets/86196556/667bae55-ecd6-4e8b-833e-61760a209b70)

Errors and warnings being displayed in the browser console:

```
Realtime got disconnected. Reconnect will be attempted in 1 seconds. <empty string> [_layout.svelte.3d312bd3.js:5:164](https://dh-sw.net/_app/immutable/entry/_layout.svelte.3d312bd3.js)
    Immutable 3
        co
        createSocket
        i

Ignoring unsupported entryTypes: layout-shift.

The resource at “https://sdh-sw.net/fonts/inter/inter-v8-latin-600.woff2” preloaded with link preload was not used within a few seconds. Make sure all preload tag attributes are set correctly. platforms

The resource at “https://dh-sw.net/fonts/inter/inter-v8-latin-regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all preload tag attributes are set correctly. platforms

The resource at “https://dh-sw.net/fonts/poppins/poppins-v19-latin-500.woff2” preloaded with link preload was not used within a few seconds. Make sure all preload tag attributes are set correctly. platforms

The resource at “https://dh-sw.net/fonts/poppins/poppins-v19-latin-600.woff2” preloaded with link preload was not used within a few seconds. Make sure all preload tag attributes are set correctly. platforms

The resource at “https://dh-sw.net/fonts/poppins/poppins-v19-latin-700.woff2” preloaded with link preload was not used within a few seconds. Make sure all preload tag attributes are set correctly. platforms

The resource at “https://dh-sw.net/fonts/source-code-pro/source-code-pro-v20-latin-regular.woff2” preloaded with link preload was not used within a few seconds . Make sure all preload tag attributes are set correctly.
```

### 🎲 Appwrite version

Version 1.3.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Cloudflare, Ubuntu server (latest version), Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by senali-d** [comment]
I would like to work on this. Can you assign it to me?
