### ISSUE TITLE
Add the option to disable the console AI

### ISSUE THREAD

**Issue by aabmets** [appwrite/console#555]
This is necessary for enterprise use cases when working with confidential or  proprietary data that must not leave the premises.
While you have promp-engineered  ChatGPT to only respond to queries about the Appwrite console, the contents of the query are nevertheless sent to OpenAI for inference, including any proprietary or confidential data that the user might erroneously insert into the prompt.
To be able to ensure that company-wide infosec policies are followed, it is adamant that the ability to use the built-in AI can be optionally disabled by a system administrator.

**Comment by stnguyen90** [comment]
@aabmets, thanks for raising this issue! 🙏🏼 The AI prompt should be hidden if the [Assistant environment variable](https://appwrite.io/docs/environment-variables#assistant) isn't set. 

![image](https://github.com/appwrite/console/assets/1477010/1721ff3a-8a4f-457b-a66d-28c067034e2b)

Is there something more you were asking for?

**Comment by aabmets** [comment]
Ok, thanks, it works for self-hosting.
