### ISSUE TITLE
🐛 Bug Report: Document IDs Don't Update when Changing Collections

### ISSUE THREAD

**Issue by JayPokale** [appwrite/console#581]
### 👟 Reproduction steps

This issue was uploaded on [appwrite/appwrite](https://github.com/appwrite/appwrite) by @stnguyen90.
URL of original issue: [here](https://github.com/appwrite/appwrite/issues/6497)

1. Have multiple collections with multiple documents
2. Have your view set up so the ID is truncated
3. Switch between Collections

### 👍 Expected behavior

The IDs update

### 👎 Actual Behavior

The IDs don't update:
<video src="https://user-images.githubusercontent.com/1477010/272751382-b55b99e8-81b3-416a-a32c-a348e95dfbd7.mov"></video>

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

Linux

### 🧱 Your Environment

The video was recorded on an older version, but the bug is still prevalent on Appwrite Cloud (1.4.4).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by senali-d** [comment]
I would like to work on this. Can you assign it to me?
