### ISSUE TITLE
🐛 Bug Report: Contents overflowing in the Sessions section (Not Responsive)

### ISSUE THREAD

**Issue by Sreejit-Sengupto** [appwrite/console#614]
### 👟 Reproduction steps
![image](https://github.com/appwrite/console/assets/69980616/7dff5eae-acc3-4a63-b056-2c77e947d3cf)

1. Create a user.
2. Go to the Auth Section.
3. Click on the user.
4. Navigate to the Sessions

### 👍 Expected behavior

The contents should not overflow.

### 👎 Actual Behavior

Contents(the table) is overflowing in the x-direction

### 🎲 Appwrite version

Version 1.4.x

### 💻 Operating system

Windows

### 🧱 Your Environment

I am using Appwrite 1.4.9

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by sourabpramanik** [comment]
@TGlide anyone working on this? If not can I take it please? I am looking to make my first contribution to Appwrite

**Comment by TGlide** [comment]
> @TGlide anyone working on this? If not can I take it please? I am looking to make my first contribution to Appwrite

Go for it!

**Comment by sourabpramanik** [comment]
@TGlide What do you think? Am I missing anything? Following the similar design pattern.

![overflow fix](https://github.com/appwrite/console/assets/61370770/4e56c9df-4e94-4c1e-b118-ee149f208b72)

**Comment by TGlide** [comment]
> @TGlide What do you think? Am I missing anything? Following the similar design pattern.
> 
> ![overflow fix](https://private-user-images.githubusercontent.com/61370770/291367086-4e56c9df-4e94-4c1e-b118-ee149f208b72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjMyNzUsIm5iZiI6MTcwMjkyMjk3NSwicGF0aCI6Ii82MTM3MDc3MC8yOTEzNjcwODYtNGU1NmM5ZGYtNGU5NC00YzFlLWIxMTgtZWUxNDlmMjA4YjcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGNlZDk1ZTQ1MjJhMWI1ZTIyZTFhMTAxNGMzMGQwNzVlMTA3ZDJmM2M5MzU2Mjc5NWQ1YTg5YWFiMWRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5gQhhOfKDBnkuxXyKU7B9bFaQ1T3LS6crERVm_O4A0) [ ![overflow fix](https://private-user-images.githubusercontent.com/61370770/291367086-4e56c9df-4e94-4c1e-b118-ee149f208b72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjMyNzUsIm5iZiI6MTcwMjkyMjk3NSwicGF0aCI6Ii82MTM3MDc3MC8yOTEzNjcwODYtNGU1NmM5ZGYtNGU5NC00YzFlLWIxMTgtZWUxNDlmMjA4YjcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGNlZDk1ZTQ1MjJhMWI1ZTIyZTFhMTAxNGMzMGQwNzVlMTA3ZDJmM2M5MzU2Mjc5NWQ1YTg5YWFiMWRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5gQhhOfKDBnkuxXyKU7B9bFaQ1T3LS6crERVm_O4A0) ](https://private-user-images.githubusercontent.com/61370770/291367086-4e56c9df-4e94-4c1e-b118-ee149f208b72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjMyNzUsIm5iZiI6MTcwMjkyMjk3NSwicGF0aCI6Ii82MTM3MDc3MC8yOTEzNjcwODYtNGU1NmM5ZGYtNGU5NC00YzFlLWIxMTgtZWUxNDlmMjA4YjcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGNlZDk1ZTQ1MjJhMWI1ZTIyZTFhMTAxNGMzMGQwNzVlMTA3ZDJmM2M5MzU2Mjc5NWQ1YTg5YWFiMWRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5gQhhOfKDBnkuxXyKU7B9bFaQ1T3LS6crERVm_O4A0) [ ](https://private-user-images.githubusercontent.com/61370770/291367086-4e56c9df-4e94-4c1e-b118-ee149f208b72.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MjMyNzUsIm5iZiI6MTcwMjkyMjk3NSwicGF0aCI6Ii82MTM3MDc3MC8yOTEzNjcwODYtNGU1NmM5ZGYtNGU5NC00YzFlLWIxMTgtZWUxNDlmMjA4YjcyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE4MDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGNlZDk1ZTQ1MjJhMWI1ZTIyZTFhMTAxNGMzMGQwNzVlMTA3ZDJmM2M5MzU2Mjc5NWQ1YTg5YWFiMWRmYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k5gQhhOfKDBnkuxXyKU7B9bFaQ1T3LS6crERVm_O4A0)

It's better to add scroll to it, so that mobile users can access all the content available. We have examples throughout the console.

```html
<div class="table-with-scroll">
  <div class="table-wrapper">
  </div>
</div>
```

**Comment by sourabpramanik** [comment]
Thanks will look into that.

**Comment by sourabpramanik** [comment]
Hey @TGlide can you please review my PR? If any other changes needed to be done please let me know.
