### ISSUE TITLE
🚀 Improvement: Use Local Time for Premium Support Timings

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/console#933]
### 🔖 Feature description

Currently the timings for premium support are listed in UTC time format which may not be easy to convert to local time. Using a user's local standard time would be much easier to understand the exact timings for the support.

---

Current -
<table>
<tr>
<td>
<img src="https://github.com/appwrite/console/assets/20625965/376695d7-7802-48cb-ac55-37a38f039aaf" height="275">
</td>

<td>
<img src="https://github.com/appwrite/console/assets/20625965/92b856d5-b7e6-40bc-9c61-1f8930d2aec1" height="275">
</td>
</tr>
</table>

---

Suggestion -

<table>
<tr>
<td>
<img src="https://cdn.discordapp.com/attachments/870534256324124692/1214828587404886118/Support_timings_in_local_time.png?ex=65fa8849&is=65e81349&hm=a488fe784a20bef957da3240a3329883bda68fb10e5311f4d96cc0a3a323d103&" height="275">
</td>

<td>
<img src="https://cdn.discordapp.com/attachments/870534256324124692/1214830201477791744/Support_Timings_in_IST.png?ex=65fa89ca&is=65e814ca&hm=d435a2a057226099e2001985afcb87f732089d47c32a3d4b07e78dc877d70d8f&" height="275">
</td>
</tr>
</table>

### 🎤 Pitch

It would make it easier to understand support timings.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@ItzNotABug. thanks for creating this issue! 🙏🏼 Let me bring it up to the team.

If we move forward with this, would you like to work on making the change?

**Comment by stnguyen90** [comment]
Go the green light for this so I'm going to open this up for contributors.

**Comment by ItzNotABug** [comment]
> @ItzNotABug. thanks for creating this issue! 🙏🏼 Let me bring it up to the team.
> 
> If we move forward with this, would you like to work on making the change?

@stnguyen90 I could definitely give this a try.

I see these two pages here -
1. https://github.com/appwrite/console/blob/main/src/routes/console/supportWizard.svelte
2. https://github.com/appwrite/console/blob/main/src/lib/components/support.svelte

I assume we'd use `Date()` based logic but should that go in the same page's `<script>` tag or somewhere else?

**Comment by stnguyen90** [comment]
@ItzNotABug, yep! This is a little different since it's a day/time range, but maybe some of the following will help you in formatting it right:

https://github.com/appwrite/console/blob/0700c5cc45c1093a96aa279dfea815a64ac549f5/src/routes/console/project-%5Bproject%5D/messaging/wizard/step3.svelte#L33-L41

We have various helpers [here](https://github.com/appwrite/console/blob/1.5.x/src/lib/helpers/date.ts) too.
