### ISSUE TITLE
🐛 Bug Report: Incorrect Message When Email Sending Fails

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/console#977]
### 👟 Reproduction steps

A failed email's details show -
**The message has been sent with errors. Please refer to the logs below for more information.**

The email will not be sent here in almost all the cases I tested if there was an error.

### 👍 Expected behavior

Show - **The message could not be sent due to an error. Please refer to the logs below for more information.**

### 👎 Actual Behavior

Message is said to **sent** with errors which is or might not be true.

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

MacOS

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by chenparnasa** [comment]
@stnguyen90 I agree, the new suggestion looks good to me 👍
