### ISSUE TITLE
🐛 Bug Report: Incorrect Message When Updating Events For Functions

### ISSUE THREAD

**Issue by ItzNotABug** [appwrite/console#978]
### 👟 Reproduction steps

1. Go to your Function Settings
2. Add any event > Click `Update`
3. Success Message shows as - **Permissions have been updated**.

### 👍 Expected behavior

Message should be - **Events have been updated**.

### 👎 Actual Behavior

Message says - **Permissions have been updated** which is wrong.

### 🎲 Appwrite version

Appwrite Cloud

### 💻 Operating system

MacOS

### 🧱 Your Environment

This also affects `1.5.x` on a localhost setup along with `1.4.13` on Cloud.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatthijsDV2004** [comment]
I can fix this.

**Comment by DH-555** [comment]
Looks like this is solved (PR merged).
@ItzNotABug Can you confirm?

**Comment by ItzNotABug** [comment]
> Looks like this is solved (PR merged). [@ItzNotABug](https://github.com/ItzNotABug) Can you confirm?

Seems to be fixed. Closing.
