### ISSUE TITLE
🐛 Bug Report: Array deletion not updating

### ISSUE THREAD

**Issue by SplinterNight1** [appwrite/console#996]
### 👟 Reproduction steps

just create string array attributes fill it, try to delete only one, the button for update not updating to red color, so no posisbility to update

### 👍 Expected behavior

update

### 👎 Actual Behavior

can't delete strings in array one by one, can only by deleting all and click on update

### 🎲 Appwrite version

Version 1.5.x

### 💻 Operating system

Linux

### 🧱 Your Environment

appwrite/appwrite:1.5.1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
I can't seem to reproduce this on the latest branch so it's probably good now/soon:

https://github.com/appwrite/console/assets/1477010/ea138fc8-0509-4f81-a22b-1e5e5e0032d0
